### PR TITLE
Compatibility with PHP 8.1

### PR DESCRIPTION
**Pull request by BenMorel**

### CODE REVIEW

**Comment by BenMorel** [comment]
The issue on PHP 8.1:

> PHP Fatal error:  Could not check compatibility between PHPUnit\PharIo\Manifest\AuthorCollection::getIterator(): PHPUnit\PharIo\Manifest\AuthorCollectionIterator and IteratorAggregate::getIterator(): Traversable, because class PHPUnit\PharIo\Manifest\AuthorCollectionIterator is not available in phar:///home/runner/work/phpunit-globals/phpunit-globals/tests/phar/tools/phpunit/phar-io-manifest/values/AuthorCollection.php on line 33

seems to be the same as https://github.com/sebastianbergmann/phpunit/issues/4740

If I understand the discussion correctly, this should have been fixed by using `phar-io/manifest: 2.0.3`, but it's not.

Any idea how to fix this?

**Comment by jakzal** [comment]
Currently failing on: 

```
PHP Fatal error:  Could not check compatibility between PHPUnit\PharIo\Manifest\AuthorCollection::getIterator(): PHPUnit\PharIo\Manifest\AuthorCollectionIterator and IteratorAggregate::getIterator(): Traversable, because class PHPUnit\PharIo\Manifest\AuthorCollectionIterator is not available in phar:///home/runner/work/phpunit-globals/phpunit-globals/tests/phar/tools/phpunit/phar-io-manifest/values/AuthorCollection.php on line 33
```

**Comment by jakzal** [comment]
Thanks for working on it!

**Comment by jakzal** [comment]
Can you merge the master branch please?

**Comment by BenMorel** [comment]
@jakzal Done! Looks like the CI still needs approval.

**Comment by jakzal** [comment]
Thanks @BenMorel 🍺 

I'll make a release later today. Before that I'd like to take a look at things that were disabled for PHP 8.0 which could now be re-enabled (some steps on the CI and some in the Makefile). Unless you'd like to do that? ;)

**Comment by BenMorel** [comment]
Thank you! I'll try to have a look tonight, if you've not already done it ;)

**Pull request merged**
